apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80         # Port on the Load Balancer
      targetPort: 5000   # Port the Flask app is actually using
  type: LoadBalancer
